### ISSUE TITLE
Fetch correct Rating and Review from the Database and display in details of places which is displayed when clicking on the place.

### ISSUE THREAD

**Issue by CyrilMishra** [ContriHUB/Sheher#14]

**Comment by kunal2812** [comment]
@CyrilMishra how is the overall rating for places to be calculated ? I mean is it supposed to be the mean of security, sanitization, safety and overall fun ratings over all the reviews of the places ?

**Comment by CyrilMishra** [comment]
> @CyrilMishra how is the overall rating for places to be calculated ? I mean is it supposed to be the mean of security, sanitization, safety and overall fun ratings over all the reviews of the places ?

Yes , it is the mean of all of the mentioned matrix of rating.

**Comment by kunal2812** [comment]
Sorry for bugs. 
When I logged into the app there was some data already in the db so I thought maybe I have to leave the db as it is.
I have made the changes as required. Please verify.
