### ISSUE TITLE
Give an attractive background image to login/signup page.

### ISSUE THREAD

**Issue by CyrilMishra** [ContriHUB/Sheher#21]

**Comment by Umang1103** [comment]
@CyrilMishra can I work on this issue?

**Comment by CyrilMishra** [comment]
> @CyrilMishra can I work on this issue?

Could I Know you are from which college ?

**Comment by Umang1103** [comment]
> > @CyrilMishra can I work on this issue?
> 
> Could I Know you are from which college ?

3rd year from MNNIT. This issue is not on the contrihub website. That's why I asked for its assignment

**Comment by CyrilMishra** [comment]
> > > @CyrilMishra can I work on this issue?
> > 
> > Could I Know you are from which college ?
> 
> 3rd year from MNNIT. This issue is not on the contrihub website. That's why I asked for its assignment

It will be there in a minute, you request there only it will be easy for assigning points.

**Comment by prackode** [comment]
is this issue currently assigned to anyone, @CyrilMishra ?

**Comment by CyrilMishra** [comment]
Nope

**Comment by prackode** [comment]
I've made a request for the same on the site...

**Comment by CyrilMishra** [comment]
> I've made a request for the same on the site...

Before you made the request , it was made by someone else. Sorry for that 
You could request another issues.

**Comment by prackode** [comment]
> Collaborator

so can you pls assign me #20 now..
