### ISSUE TITLE
Add Map to The About Place popup showed when place icon is clicked on. 

### ISSUE THREAD

**Issue by CyrilMishra** [ContriHUB/Sheher#34]
Add Location fields to place details. (Accessible only from Django Admin Portal)
Show place Location in the map in place popup opened when clicked on.

**Comment by MauryaRitesh** [comment]
can you assign me this issue @CyrilMishra ?
currently its not present on the website for assignment

**Comment by CyrilMishra** [comment]
> can you assign me this issue @CyrilMishra ?
> currently its not present on the website for assignment

It is now live on website.
