### ISSUE TITLE
Profile Pic Fetching Issue.

### ISSUE THREAD

**Issue by CyrilMishra** [ContriHUB/Sheher#36]
Profile Pic is not getting is not getting fetched in profile page and add profile pic in circle in homepage.

**Comment by prackode** [comment]
can you assign me this issue @CyrilMishra ?
currently its not present on the website for assignment...

**Comment by CyrilMishra** [comment]
It is there now.

**Comment by prackode** [comment]
profile pic is getting fetched already on profile page!!
and should I add the profile pic in place of the email shown on homepage or profile pic and email both ??

**Comment by CyrilMishra** [comment]
> profile pic is getting fetched already on profile page!!
> and should I add the profile pic in place of the email shown on homepage or show profile pic and email both ?? @CyrilMishra

both
