### ISSUE TITLE
Change Navigation bar Colour

### ISSUE THREAD

**Issue by CyrilMishra** [ContriHUB/Sheher#40]
Currently the navbar colour is according to the Background.
Task is to fix the navigation bar colour to Black for all pages.

**Comment by JanitaRiyaz** [comment]
i want to work on it.plz asssign this to me.

**Comment by CyrilMishra** [comment]
> i want to work on it.plz asssign this to me.

You are from which college?

**Comment by JanitaRiyaz** [comment]
from Bahuudin zikriya university(BZU, multan)

**Comment by JanitaRiyaz** [comment]
> > i want to work on it.plz asssign this to me.
> 
> You are from which college?

Bauddin zikriya college(BZU, Multan)

**Comment by CyrilMishra** [comment]
You cannot work on this issue, all of the issues under contrihub is under Avishkar(Tech Fest) and for students of MNNIT, Allahabad.
