### ISSUE TITLE
Fix login and signup forms

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#59]
![image](https://github.com/ContriHUB/Sheher/assets/59749539/76623f7d-a922-4716-a8ad-5bfc3b4b6b1c)

The primary task is to remove the background from both forms to make the page visually appealing. 

Note:
- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by dhruvm911** [comment]
sir can you assign this issue to me?

**Comment by kunal2812** [comment]
Please request through Contrihub
