### ISSUE TITLE
Create a message for Sign up and Invalid Credentials just like sign in and sign out

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#60]
![image](https://github.com/ContriHUB/Sheher/assets/59749539/e4610da6-ea20-4124-b6ec-a61cbf376bbf)

### Problem
There is an inconsistency in UX regarding notifications. When users log in or log out, a message pops up in the corner of the screen to provide feedback. However, this does not happen when users sign up or enters invalid credentials during the sign in process. A HTTP Response is returned in case of sign up and nothing happens when invalid creds are entered, which may be confusing for users.

![image](https://github.com/ContriHUB/Sheher/assets/59749539/455025dd-4f71-4a40-a43b-612bd81d2649)

### Expected Behavior
Consistency in user experience is important for a seamless and intuitive application. The behavior for all three actions (login, logout, and sign-up) should be consistent. When the user signs on Sheher a similar message should be shown in the corner of screen on the /register page. Similarly while entering wrong credentials

Note:
- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by kunal2812** [comment]
@samuels165 Sorry can't assign it to you. This is for a college event related to open source contributions.

**Comment by eleensmathew** [comment]
Will I not receive points for my fifth issue?

**Comment by kunal2812** [comment]
Already given. Check your profile

**Comment by eleensmathew** [comment]
oh ok thanks 👍
