### ISSUE TITLE
Gender is not asked during signup but available in profile section

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#61]
### Problem

During the user signup process in the Sheher, gender information is not collected from users. However, gender is available in the profile section, which results in incomplete user profiles. Additionally, there is an inconsistency in the theme of the profile section compared to the Sheher theme.

![image](https://github.com/ContriHUB/Sheher/assets/59749539/6572c95a-abaf-44a8-bf0e-94fe4a28b153)

### Expected Behaviour

- During the user signup process, users should be able to select their gender using a dropdown or radio button.
Gender information should be stored in the database (Gender field is already there in the model)
- The profile section should reflect the selected gender, and its visual theme should align with the Sheher application's theme (Will give bonus points for that)

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by eleensmathew** [comment]
What do you mean by theme exactly?Am I just supposed to change the light blue plain background of the profile section to the homepage background? @kunal2812

**Comment by kunal2812** [comment]
The profile section should look like it is part of the application. In general, fonts and styles should remain consistent across all pages. Make any necessary changes accordingly.
