### ISSUE TITLE
Log Out not working in Report Page

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#63]
### Problem

When a user is signed in and clicks on the Report page, the "Log out" option does not perform the intended task (/Places/complaints)

![image](https://github.com/ContriHUB/Sheher/assets/59749539/29aa63f9-1b36-49a3-9288-c59d7db4988d)

### Expected Behaviour

The "Log out" button should log the user out when clicked on the Report page or any other page within the application. The logout functionality is already implemented but does not work on this page.

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by tmatheas** [comment]
@kunal2812  Can you assign the issue to me ? Also can you add `Hacktoberfest` label to the issue ?

**Comment by kunal2812** [comment]
@tmatheas This is for a college event related to open source. Sorry can't assign it to you.
