### ISSUE TITLE
Add Weather Information in Place Modal using some weather api

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#64]
Weather information can be a valuable addition to help users plan their trips effectively. This issue aims to implement a functionality to display weather conditions for a place using a weather API (You can use latitude and longitude coordinates of the place which are already stored in the Place model)
When users click on a place in the app, they should be able to view the real time weather conditions for that place in that modal

![image](https://github.com/ContriHUB/Sheher/assets/59749539/d2d95180-df24-4227-8231-47f9cd87d3e4)

(Weather info should be shown here above all review sections. Make the information on place modal more organised. Extra points for neat work)

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by eleensmathew** [comment]
Can I work on this?

**Comment by kunal2812** [comment]
Don't push your creds, just mention the API you are using in the PR description
