### ISSUE TITLE
Implement a blog functionality for Visitors

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#65]
Add a "Blog" section to the app's navigation bar, providing users with easy access to the blog functionality. Enable registered users to create and publish their travel blogs, stories, and articles. Allow users to upload photos to accompany their blog posts.
Create a separate page accessible through the "Blog" section where all user-generated blogs are listed. Display blogs in a sorted order, with the most recent posts at the top.
When a user clicks on a blog entry in the list, it should expand to display the full content of the blog post, including text and accompanying photos. Implement "Like" and "Dislike" buttons for each blog post, allowing users to express their preference.
Include a comment section for each blog post, enabling users to engage in discussions and leave feedback.
Utilize the existing review/comment functionality from the "Places" section and adapt it for blog posts.
(Will give bonus for neat work 😋)

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by Nandika-A** [comment]
@kunal2812 Do we have to implement the frontend as well?

**Comment by kunal2812** [comment]
> @kunal2812 Do we have to implement the frontend as well?

Yes
