### ISSUE TITLE
Make Profile Picture Optional During Sign-up

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#66]
### Problem

The user is not able to sign up if he does not upload profile picture which should be optional. 

### Expected Behaviour

If the user does not uplaods profile picture a default avatar can be used and users should be able to create an account

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by kunal2812** [comment]
@eleensmathew Please request through Contrihub

**Comment by eleensmathew** [comment]
This issue is not present in the contrihub dashboard at the moment. How do I proceed?

**Comment by kunal2812** [comment]
Available now

**Comment by eleensmathew** [comment]
@kunal2812 I have made a pull request to fix this issue

**Comment by kunal2812** [comment]
Submit PR link on contrihub

**Comment by eleensmathew** [comment]
ok its done 👍Thanks for letting me know.
