### ISSUE TITLE
Remove empty file "hello.txt"

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#67]
There is an empty file in the repo "hello.txt". Remove it.

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by tmatheas** [comment]
@kunal2812 Can you assign the issue to me ?

**Comment by Aqua-16** [comment]
@kunal2812 Sir could you also please verify the submission on ContriHub as well, that would be great.
