### ISSUE TITLE
Implement "Top Blogs" Section on Home Page

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#80]
Create a "Top Blogs" section (below the "Places" section) on the Home page which displays the top blogs based on Likes/Dislikes ratio (Take care of 0/0 case). The section should include a grid layout for displaying blog cards.
Each blog card should include the following information:
- Title of the blog
- Thumbnail image
- Author's email
- The number of Likes and Dislikes.
- A link to the full blog post (Or create a modal similar to Place in the Places section)

The "Top Blogs" section should display a reasonable number of blogs (2 rows) to avoid overwhelming the user. The "Top Blogs" section should be responsive and adapt to various screen sizes

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by Nandika-A** [comment]
@kunal2812 I have implemented this in PR#83. Please check this.

**Comment by kunal2812** [comment]
@Nandika-A Request again on contrihub and then submit PR from there to get it reviewed.

**Comment by Nandika-A** [comment]
@kunal2812 It shows that I cannot make this request.

**Comment by kunal2812** [comment]
You'll have to accept penalty of few points for late PR. Do you want to request again ?

**Comment by Nandika-A** [comment]
> You'll have to accept penalty of few points for late PR. Do you want to request again ?

Okay sir

**Comment by kunal2812** [comment]
Try requesting now

**Comment by Nandika-A** [comment]
@kunal2812 still I can't make request.

**Comment by kunal2812** [comment]
Try now
