### ISSUE TITLE
Replace "Places" Section with "Top Places" and Create Separate "All Places" Page

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Sheher#81]
- The existing "Places" section on the Home page should be replaced with a new "Top Places" section
- Keep the Place card as it currently is (No changes needed for the design part)
- The "Top Places" section should display places based on their user rating, with the highest-rated places at the top (2 rows of cards)
- "All Places" in nav bar should provide access to the comprehensive list of all places
- The "All Places" page should be designed in accordance with the Sheher theme, similar to the "Blogs" page. It should display all available places, maintaining the card structure and design for each place.
- When the user clicks on both "Top Places" cards and "All Places" cards the modals should open (already designed, no changes needed there)

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by eleensmathew** [comment]
Is this issue open? Can i work on this?

**Comment by kunal2812** [comment]
Currently assigned to @Manan-Arora31
